version: '3'
services: 
  mysql_db_container:
    image: 'mysql'
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: passw0rdR00tB3Ec0m2024
      MYSQL_DATABASE: be-ecom
      MYSQL_USER: us3rEc0m
      MYSQL_PASSWORD: passw0rdB3Ec0m2024
    networks: 
      - 'database-net'
    volumes: 
      - mysql_db_data_container:/var/lib/mysql
  
  adminer:
    image: 'adminer'
    ports: 
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container  
    networks: 
      - 'database-net'
networks:
  database-net:
volumes:
  mysql_db_data_container:

